version: '3.4'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=posgres
      - POSTGRES_PASSWORD=posgres
      - POSTGRES_DB=gvisor
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh", "-c", "pg_isready", "-d", "gvisor", "-U", "posgres"]
      interval: 10s
      timeout: 3s
      retries: 2

  broker:
    environment:
      - POSTGRES_ADDR=postgres://posgres:posgres@postgres:5432/gvisor
    depends_on:
      postgres:
        condition: service_healthy
    build: ./broker/
    ports:
      - "12001:12001"

  wsserver:
    environment:
      - POSTGRES_ADDR=postgres://posgres:posgres@postgres:5432/gvisor
    depends_on:
      postgres:
        condition: service_healthy
    build: ./ws_server/
    ports:
      - "3001:3001"

  webview:
    environment:
      - WSSOCKET_ADDR='wsserver:3001'
    depends_on:
      - wsserver
    build: ./WebView/
    ports:
      - "3000:3000"
